spring.application.name=pokeidle
spring.datasource.url=${POKEIDLE_DB_URL:jdbc:sqlserver://localhost:1433;databaseName=DB_POKEIDLE;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${POKEIDLE_DB_USERNAME:sa}
spring.datasource.password=${POKEIDLE_DB_PASSWORD:SenhaForte123}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
pokeapi.base-url=https://pokeapi.co/api/v2
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs
